### ISSUE TITLE
Подготовить и опубликовать описание команды на странице Wiki

### ISSUE THREAD

**Issue by Sly8Fox** [Sly8Fox/team-development#6]
- [ ]  Подготовить и опубликовать описание команды на [странице Wiki]( https://github.com/Sly8Fox/team-development/wiki/%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA%D0%B8-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B)

_Originally posted by @Sly8Fox in https://github.com/Sly8Fox/team-development/issues/1#issuecomment-1052363527_

**Comment by KattyOG** [comment]
Добавлено [описание](https://github.com/Sly8Fox/team-development/wiki/%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA%D0%B8-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B/eecfdb5393883d4ac63f229f976f0ea63eaac058) команды
